[build-system]
requires = [
    "setuptools>=47",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
dependencies = [
    "markdown==2.6.11",
    "Jinja2==3.0.1",
    "python-slugify==5.0.2",
]
