import unittest
import markdown
import os

from csfg_extension import CSFGExtension
from processors.panel import *

class PanelTest(unittest.TestCase):

    def setUp(self):
        self.md = markdown.Markdown(extensions=[CSFGExtension()])
        self.test_file_path = 'tests/assets/panel/{}.txt'
        self.generated_file_path = 'tests/assets/panel/generated/{}.txt'
        self.expected_file_path = 'tests/assets/panel/expected/{}.txt'

        # delete files generated by previously running these tests
        existing_generated_files = [f for f in os.listdir('tests/assets/panel/generated/')]
        for f in existing_generated_files:
            os.remove(self.generated_file_path.format(f.rstrip('.txt'))) # removing repeated '.txt'

    def test_match_false(self):
        test_string = open(self.test_file_path.format('fail_string')).read()
        self.assertFalse(PanelBlockProcessor(self.md.parser).test(None, test_string), msg='"{}"'.format(test_string))
        pass

    def test_match_true(self):
        pass

    def tearDown(self):
        self.md = None


