name: Documentation

on: [push]

jobs:
  build-documentation:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v4.3.1
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Build documentation
        run: sphinx-build -a -W -E -b html docs/source/ docs/build/
